-- M04 extensible category attribute profiles. V5 stays immutable.
CREATE TABLE public.categoria_perfil_atributos (
    categoria_codigo text NOT NULL REFERENCES public.categoria_espacio(codigo) ON DELETE RESTRICT,
    version integer NOT NULL CHECK (version > 0),
    perfil jsonb NOT NULL CHECK (jsonb_typeof(perfil) = 'object'),
    creado_en timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (categoria_codigo, version)
);
CREATE TABLE public.espacio_caracteristicas (
    espacio_id uuid PRIMARY KEY REFERENCES public.espacio(id) ON DELETE CASCADE,
    categoria_codigo text NOT NULL,
    perfil_version integer NOT NULL,
    valores jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(valores) = 'object' AND octet_length(valores::text) <= 16384),
    actualizado_en timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (categoria_codigo, perfil_version) REFERENCES public.categoria_perfil_atributos(categoria_codigo, version) ON DELETE RESTRICT
);
ALTER TABLE public.espacio ADD CONSTRAINT espacio_id_categoria_unique UNIQUE (id, categoria_codigo);
ALTER TABLE public.espacio_caracteristicas ADD CONSTRAINT espacio_caracteristicas_category_fk FOREIGN KEY (espacio_id, categoria_codigo) REFERENCES public.espacio(id, categoria_codigo) ON DELETE CASCADE;
INSERT INTO public.categoria_perfil_atributos(categoria_codigo,version,perfil) VALUES
('oficina',1,'{"category_code":"oficina","schema_version":1,"attributes":[{"code":"puestos_trabajo","label":"Puestos de trabajo","type":"integer","filter_candidate":false,"minimum":1,"maximum":2147483647},{"code":"mobiliario_incluido","label":"Mobiliario incluido","type":"boolean","filter_candidate":false},{"code":"tipo_uso_oficina","label":"Tipo de uso","type":"enum","filter_candidate":false,"options":["privada","compartida"]},{"code":"escritorios","label":"Escritorios","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"sillas_trabajo","label":"Sillas de trabajo","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"salas_reunion_disponibles","label":"Salas de reunión disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"impresora_disponible","label":"Impresora disponible","type":"boolean","filter_candidate":false},{"code":"wifi","label":"Wi-Fi","type":"boolean","filter_candidate":false},{"code":"energia_electrica","label":"Energía eléctrica","type":"boolean","filter_candidate":false},{"code":"banos_disponibles","label":"Baños disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"climatizacion","label":"Climatización","type":"enum_list","filter_candidate":false,"options":["aire_acondicionado","calefaccion","ventilacion_mecanica"]}]}'::jsonb),
('sala_multiproposito',1,'{"category_code":"sala_multiproposito","schema_version":1,"attributes":[{"code":"disposiciones_admitidas","label":"Disposiciones admitidas","type":"enum_list","filter_candidate":false,"options":["auditorio","mesa_reunion","aula","espacio_libre"]},{"code":"sillas_disponibles","label":"Sillas disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"proyector","label":"Proyector","type":"boolean","filter_candidate":false},{"code":"mesas_disponibles","label":"Mesas disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"pantalla","label":"Pantalla","type":"boolean","filter_candidate":false},{"code":"pizarra","label":"Pizarra","type":"boolean","filter_candidate":false},{"code":"videoconferencia","label":"Videoconferencia","type":"boolean","filter_candidate":false},{"code":"equipo_audio","label":"Equipo de audio","type":"boolean","filter_candidate":false},{"code":"wifi","label":"Wi-Fi","type":"boolean","filter_candidate":false},{"code":"energia_electrica","label":"Energía eléctrica","type":"boolean","filter_candidate":false},{"code":"banos_disponibles","label":"Baños disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"climatizacion","label":"Climatización","type":"enum_list","filter_candidate":false,"options":["aire_acondicionado","calefaccion","ventilacion_mecanica"]}]}'::jsonb),
('bodega',1,'{"category_code":"bodega","schema_version":1,"attributes":[{"code":"altura_util_m","label":"Altura útil","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"volumen_util_m3","label":"Volumen útil","type":"number","filter_candidate":false,"unit":"m³","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"acceso_carga","label":"Acceso de carga","type":"enum","filter_candidate":false,"options":["peatonal","vehiculo_liviano","furgon","camion"]},{"code":"ancho_acceso_m","label":"Ancho de acceso","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"altura_acceso_m","label":"Altura de acceso","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"carro_carga_disponible","label":"Carro de carga disponible","type":"boolean","filter_candidate":false},{"code":"muelle_carga","label":"Muelle de carga","type":"boolean","filter_candidate":false},{"code":"tipo_almacenamiento","label":"Tipo de almacenamiento","type":"enum","filter_candidate":false,"options":["seco","temperatura_controlada","refrigerado"]}]}'::jsonb),
('estacionamiento',1,'{"category_code":"estacionamiento","schema_version":1,"attributes":[{"code":"largo_plaza_m","label":"Largo de plaza","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"ancho_plaza_m","label":"Ancho de plaza","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"vehiculos_admitidos","label":"Vehículos admitidos","type":"enum_list","filter_candidate":false,"options":["motocicleta","automovil","suv","furgon"]},{"code":"altura_maxima_m","label":"Altura máxima","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"techado","label":"Techado","type":"boolean","filter_candidate":false},{"code":"tipo_acceso","label":"Tipo de acceso","type":"enum","filter_candidate":false,"options":["abierto","porton_manual","porton_automatico"]},{"code":"carga_electrica","label":"Carga eléctrica","type":"boolean","filter_candidate":false}]}'::jsonb),
('local_flexible',1,'{"category_code":"local_flexible","schema_version":1,"attributes":[{"code":"acceso_nivel_calle","label":"Acceso a nivel de calle","type":"boolean","filter_candidate":false},{"code":"vitrina","label":"Vitrina","type":"boolean","filter_candidate":false},{"code":"frente_m","label":"Frente","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"mostradores","label":"Mostradores","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"probadores","label":"Probadores","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"bodega_apoyo_m2","label":"Bodega de apoyo","type":"number","filter_candidate":false,"unit":"m²","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"iluminacion_exhibicion","label":"Iluminación de exhibición","type":"boolean","filter_candidate":false},{"code":"wifi","label":"Wi-Fi","type":"boolean","filter_candidate":false},{"code":"energia_electrica","label":"Energía eléctrica","type":"boolean","filter_candidate":false},{"code":"banos_disponibles","label":"Baños disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"climatizacion","label":"Climatización","type":"enum_list","filter_candidate":false,"options":["aire_acondicionado","calefaccion","ventilacion_mecanica"]}]}'::jsonb),
('stand',1,'{"category_code":"stand","schema_version":1,"attributes":[{"code":"ancho_stand_m","label":"Ancho del stand","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"fondo_stand_m","label":"Fondo del stand","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"montaje_incluido","label":"Montaje incluido","type":"boolean","filter_candidate":false},{"code":"lados_abiertos","label":"Lados abiertos","type":"integer","filter_candidate":false,"minimum":1,"maximum":4},{"code":"altura_maxima_m","label":"Altura máxima","type":"number","filter_candidate":false,"unit":"m","minimum":0.01,"maximum":99999999.99,"step":0.01},{"code":"potencia_disponible_w","label":"Potencia disponible","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"paneleria","label":"Panelería","type":"boolean","filter_candidate":false},{"code":"mesas_incluidas","label":"Mesas incluidas","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"sillas_incluidas","label":"Sillas incluidas","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"energia_electrica","label":"Energía eléctrica","type":"boolean","filter_candidate":false},{"code":"wifi","label":"Wi-Fi","type":"boolean","filter_candidate":false}]}'::jsonb),
('quincho',1,'{"category_code":"quincho","schema_version":1,"attributes":[{"code":"tipo_parrilla","label":"Tipo de parrilla","type":"enum","filter_candidate":false,"options":["carbon","gas","electrica","lena","sin_parrilla"]},{"code":"techado","label":"Techado","type":"boolean","filter_candidate":false},{"code":"asientos_disponibles","label":"Asientos disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"parrillas_disponibles","label":"Parrillas disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"mesas_disponibles","label":"Mesas disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647},{"code":"lavaplatos","label":"Lavaplatos","type":"boolean","filter_candidate":false},{"code":"refrigerador","label":"Refrigerador","type":"boolean","filter_candidate":false},{"code":"utensilios_incluidos","label":"Utensilios incluidos","type":"boolean","filter_candidate":false},{"code":"agua_potable","label":"Agua potable","type":"boolean","filter_candidate":false},{"code":"energia_electrica","label":"Energía eléctrica","type":"boolean","filter_candidate":false},{"code":"banos_disponibles","label":"Baños disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647}]}'::jsonb),
('parcela_eventos',1,'{"category_code":"parcela_eventos","schema_version":1,"attributes":[{"code":"superficie_exterior_util_m2","label":"Superficie exterior útil","type":"number","filter_candidate":false,"unit":"m²","minimum":0.01,"maximum":99999999.99,"step":0.01,"order":1},{"code":"superficie_cubierta_util_m2","label":"Superficie cubierta útil","type":"number","filter_candidate":false,"unit":"m²","minimum":0.01,"maximum":99999999.99,"step":0.01,"order":2},{"code":"estacionamientos_disponibles","label":"Estacionamientos disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647,"order":3},{"code":"salon_cubierto","label":"Salón cubierto","type":"boolean","filter_candidate":false,"order":4},{"code":"cocina_disponible","label":"Cocina disponible","type":"boolean","filter_candidate":false,"order":5},{"code":"quincho_disponible","label":"Quincho disponible","type":"boolean","filter_candidate":false,"order":6},{"code":"piscina_disponible","label":"Piscina disponible","type":"boolean","filter_candidate":false,"order":7},{"code":"acceso_bus","label":"Acceso para bus","type":"boolean","filter_candidate":false,"order":8},{"code":"agua_potable","label":"Agua potable","type":"boolean","filter_candidate":false,"order":9},{"code":"energia_electrica","label":"Energía eléctrica","type":"boolean","filter_candidate":false,"order":10},{"code":"banos_disponibles","label":"Baños disponibles","type":"integer","filter_candidate":false,"minimum":0,"maximum":2147483647,"order":11}]}'::jsonb)
;

