-- M02 local-only photo and payout destination. Files remain outside PostgreSQL
-- and are always generated by the Backend. No banking details are accepted.
CREATE TABLE public.foto_perfil_sintetica_local (
    id uuid PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES public.usuario(id) ON DELETE RESTRICT,
    archivo_id uuid,
    mime_type text,
    fixture_code text NOT NULL CHECK (fixture_code='synthetic-png-v1'),
    sha256 text,
    size_bytes bigint,
    estado text NOT NULL CHECK (estado IN ('activa','reemplazada','retirada','retirada_baja')),
    creada_en timestamptz NOT NULL,
    retirada_en timestamptz,
    limpia_en timestamptz,
    intentos_limpieza integer NOT NULL DEFAULT 0 CHECK (intentos_limpieza>=0),
    proximo_intento_en timestamptz,
    ultimo_codigo_error text,
    clave_idempotencia text NOT NULL,
    CONSTRAINT foto_perfil_sintetica_archivo_ck CHECK (
        (archivo_id IS NULL AND mime_type IS NULL AND sha256 IS NULL AND size_bytes IS NULL AND limpia_en IS NOT NULL)
        OR (archivo_id IS NOT NULL AND mime_type='image/png' AND sha256 ~ '^[0-9a-f]{64}$' AND size_bytes BETWEEN 1 AND 4096 AND limpia_en IS NULL)
    ),
    CONSTRAINT foto_perfil_sintetica_retirada_ck CHECK (
        (estado='activa' AND retirada_en IS NULL) OR (estado<>'activa' AND retirada_en IS NOT NULL)
    ),
    CONSTRAINT foto_perfil_sintetica_idempotencia_ck CHECK (length(clave_idempotencia) BETWEEN 8 AND 128)
);
CREATE UNIQUE INDEX foto_perfil_sintetica_activa_owner_uq
    ON public.foto_perfil_sintetica_local(usuario_id) WHERE estado='activa';
CREATE INDEX foto_perfil_sintetica_cleanup_idx
    ON public.foto_perfil_sintetica_local(proximo_intento_en,id)
    WHERE estado<>'activa' AND archivo_id IS NOT NULL;

CREATE TABLE public.cuenta_cobro_sintetica_local (
    id uuid PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES public.usuario(id) ON DELETE RESTRICT,
    adaptador text NOT NULL CHECK (adaptador='fake-local-v1'),
    referencia_ficticia text,
    estado text NOT NULL CHECK (estado IN ('activa','reemplazada','revocada','retirada_baja')),
    creada_en timestamptz NOT NULL,
    actualizada_en timestamptz NOT NULL,
    revocada_en timestamptz,
    CONSTRAINT cuenta_cobro_sintetica_reference_ck CHECK (
        (estado='retirada_baja' AND referencia_ficticia IS NULL)
        OR (estado<>'retirada_baja' AND referencia_ficticia ~ '^demo_[a-f0-9-]{36}$')
    ),
    CONSTRAINT cuenta_cobro_sintetica_revocation_ck CHECK (
        (estado IN ('revocada','retirada_baja') AND revocada_en IS NOT NULL)
        OR (estado IN ('activa','reemplazada') AND revocada_en IS NULL)
    )
);
CREATE UNIQUE INDEX cuenta_cobro_sintetica_activa_owner_uq
    ON public.cuenta_cobro_sintetica_local(usuario_id) WHERE estado='activa';
CREATE INDEX cuenta_cobro_sintetica_owner_date_idx
    ON public.cuenta_cobro_sintetica_local(usuario_id,creada_en,id);

CREATE TABLE public.cuenta_cobro_sintetica_historial_local (
    id bigserial PRIMARY KEY,
    cuenta_id uuid NOT NULL REFERENCES public.cuenta_cobro_sintetica_local(id) ON DELETE RESTRICT,
    usuario_id uuid NOT NULL REFERENCES public.usuario(id) ON DELETE RESTRICT,
    accion text NOT NULL CHECK (accion IN ('creada','actualizada','revocada','retirada_baja')),
    ocurrida_en timestamptz NOT NULL,
    correlacion_id text NOT NULL,
    clave_idempotencia text NOT NULL CHECK (length(clave_idempotencia) BETWEEN 8 AND 128)
);
CREATE INDEX cuenta_cobro_sintetica_historial_owner_idx
    ON public.cuenta_cobro_sintetica_historial_local(usuario_id,ocurrida_en,id);

CREATE TABLE public.m02_operacion_idempotente_local (
    usuario_id uuid NOT NULL REFERENCES public.usuario(id) ON DELETE RESTRICT,
    recurso text NOT NULL CHECK (recurso IN ('foto_perfil','cuenta_cobro')),
    clave_idempotencia text NOT NULL CHECK (length(clave_idempotencia) BETWEEN 8 AND 128),
    solicitud_sha256 text NOT NULL CHECK (solicitud_sha256 ~ '^[0-9a-f]{64}$'),
    respuesta jsonb NOT NULL,
    creada_en timestamptz NOT NULL,
    PRIMARY KEY (usuario_id,recurso,clave_idempotencia)
);
CREATE INDEX m02_operacion_idempotente_retention_idx ON public.m02_operacion_idempotente_local(creada_en);
