// Package operation records the local synthetic use and return of a reserved
// space. Images are generated by the backend; arbitrary client files are not
// accepted by this prototype.
package operation

import (
	"context"
	"errors"
	"regexp"
	"time"
)

var (
	ErrInvalid   = errors.New("operation: invalid request")
	ErrNotFound  = errors.New("operation: resource not found")
	ErrConflict  = errors.New("operation: state or date conflict")
	ErrFileStore = errors.New("operation: private synthetic evidence unavailable")
	idPattern    = regexp.MustCompile(`(?i)^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)
)

const (
	CheckIn                = "checkin"
	CheckOut               = "checkout"
	Receipt                = "recepcion"
	SafetyNotice           = "ENSAYO LOCAL — EVIDENCIA SINTÉTICA; SIN VALIDEZ PROBATORIA REAL"
	CandidateRecoveryDelay = 5 * time.Minute
)

type Input struct {
	Kind         string `json:"-"`
	Comments     string `json:"comments,omitempty"`
	Observations string `json:"observations,omitempty"`
}

type Evidence struct {
	ID         string    `json:"id"`
	ContentURL string    `json:"content_url,omitempty"`
	Fixture    string    `json:"fixture_code"`
	MIME       string    `json:"mime_type"`
	SHA256     string    `json:"sha256"`
	SizeBytes  int64     `json:"size_bytes"`
	CreatedAt  time.Time `json:"created_at"`
}

type Item struct {
	ID                string         `json:"id"`
	ReservationID     string         `json:"reservation_id"`
	Kind              string         `json:"kind"`
	ActorID           string         `json:"actor_id"`
	OccurredAt        time.Time      `json:"occurred_at"`
	TimeZone          string         `json:"time_zone"`
	SyntheticLocation map[string]any `json:"synthetic_location"`
	Comments          string         `json:"comments,omitempty"`
	Observations      string         `json:"observations,omitempty"`
	Result            string         `json:"result"`
	ClaimDeadlineAt   *time.Time     `json:"claim_deadline_at,omitempty"`
	Sequence          int64          `json:"sequence"`
	Evidence          []Evidence     `json:"evidence"`
	Reused            bool           `json:"reused,omitempty"`
}

type Repository interface {
	ReserveCandidate(context.Context, string, string, string, string, time.Time) error
	BeginCandidate(context.Context, string, string, string, string) (CandidateWriter, error)
	QueueCandidateCleanup(context.Context, string, time.Time) error
	List(context.Context, string, string) ([]Item, error)
	Evidence(context.Context, string, string, string) (Evidence, error)
	ClaimCandidateCleanup(context.Context, time.Time, int) ([]string, error)
	CompleteCandidateCleanup(context.Context, string) error
	FailCandidateCleanup(context.Context, string, time.Time) error
}

type CandidateWriter interface {
	Apply(context.Context, string, string, Input, Evidence, []byte, func() time.Time) (Item, bool, error)
	QueueCleanup(context.Context, time.Time) error
	Close() error
}

type FileStore interface {
	Put(context.Context, string, []byte) error
	Get(context.Context, string) ([]byte, error)
	Delete(context.Context, string) error
}

type IDGenerator interface{ ID() (string, error) }
