// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCredentialChangedNotice = `-- name: ClaimCredentialChangedNotice :one
WITH candidate AS (
    SELECT event.id FROM public.outbox_evento_local AS event
    WHERE event.tipo = 'identidad.credencial_cambiada' AND event.entregada_en IS NULL
      AND event.disponible_en <= $2 AND (event.lease_hasta IS NULL OR event.lease_hasta <= $2)
    ORDER BY event.disponible_en, event.creada_en, event.id
    FOR UPDATE SKIP LOCKED LIMIT 1
)
UPDATE public.outbox_evento_local AS event
SET lease_hasta = $1, intentos = event.intentos + 1
FROM candidate
WHERE event.id = candidate.id
RETURNING event.id::text AS id, event.agregado_id::text AS account_id, event.intentos, event.lease_hasta AS lease_until
`

type ClaimCredentialChangedNoticeParams struct {
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	At         pgtype.Timestamptz `json:"at"`
}

type ClaimCredentialChangedNoticeRow struct {
	ID         string             `json:"id"`
	AccountID  string             `json:"account_id"`
	Intentos   int32              `json:"intentos"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) ClaimCredentialChangedNotice(ctx context.Context, arg ClaimCredentialChangedNoticeParams) (ClaimCredentialChangedNoticeRow, error) {
	row := q.db.QueryRow(ctx, claimCredentialChangedNotice, arg.LeaseUntil, arg.At)
	var i ClaimCredentialChangedNoticeRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Intentos,
		&i.LeaseUntil,
	)
	return i, err
}

const completeCredentialChangedNotice = `-- name: CompleteCredentialChangedNotice :execrows
UPDATE public.outbox_evento_local
SET entregada_en = $1, lease_hasta = NULL, ultimo_error = NULL
WHERE id = $2 AND entregada_en IS NULL AND lease_hasta = $3
`

type CompleteCredentialChangedNoticeParams struct {
	At         pgtype.Timestamptz `json:"at"`
	ID         string             `json:"id"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) CompleteCredentialChangedNotice(ctx context.Context, arg CompleteCredentialChangedNoticeParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCredentialChangedNotice, arg.At, arg.ID, arg.LeaseUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeActionToken = `-- name: ConsumeActionToken :execrows
UPDATE public.token_accion
SET consumido_en = $1
WHERE token_hash = $2
  AND expira_en > $1
  AND intentos < 5
  AND consumido_en IS NULL
  AND invalidado_en IS NULL
`

type ConsumeActionTokenParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	TokenHash  string             `json:"token_hash"`
}

func (q *Queries) ConsumeActionToken(ctx context.Context, arg ConsumeActionTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeActionToken, arg.ConsumedAt, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActionTokenEmissions = `-- name: CountActionTokenEmissions :one
SELECT count(*)::bigint
FROM public.token_accion
WHERE usuario_id = $1
  AND proposito = $2
  AND creado_en >= $3
`

type CountActionTokenEmissionsParams struct {
	AccountID string             `json:"account_id"`
	Purpose   string             `json:"purpose"`
	Since     pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountActionTokenEmissions(ctx context.Context, arg CountActionTokenEmissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActionTokenEmissions, arg.AccountID, arg.Purpose, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO public.usuario (
    id, correo_original, correo_normalizado, hash_clave, estado,
    creado_en, actualizado_en, preferencia_uso
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type CreateAccountParams struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	NormalizedEmail string             `json:"normalized_email"`
	PasswordHash    string             `json:"password_hash"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UsePreference   *string            `json:"use_preference"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.NormalizedEmail,
		arg.PasswordHash,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UsePreference,
	)
	return err
}

const createActionToken = `-- name: CreateActionToken :exec
INSERT INTO public.token_accion (
    id, usuario_id, proposito, token_hash, creado_en, expira_en,
    consumido_en, invalidado_en, intentos
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
`

type CreateActionTokenParams struct {
	ID            string             `json:"id"`
	AccountID     string             `json:"account_id"`
	Purpose       string             `json:"purpose"`
	TokenHash     string             `json:"token_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	InvalidatedAt pgtype.Timestamptz `json:"invalidated_at"`
	Attempts      int32              `json:"attempts"`
}

func (q *Queries) CreateActionToken(ctx context.Context, arg CreateActionTokenParams) error {
	_, err := q.db.Exec(ctx, createActionToken,
		arg.ID,
		arg.AccountID,
		arg.Purpose,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.InvalidatedAt,
		arg.Attempts,
	)
	return err
}

const createRightsRequest = `-- name: CreateRightsRequest :one
INSERT INTO public.solicitud_titular (id, usuario_id, tipo, canal)
VALUES ($1, $2, $3, $4)
RETURNING id::text AS id, tipo AS kind, estado AS state, solicitada_en
`

type CreateRightsRequestParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	Kind      string `json:"kind"`
	Channel   string `json:"channel"`
}

type CreateRightsRequestRow struct {
	ID           string             `json:"id"`
	Kind         string             `json:"kind"`
	State        string             `json:"state"`
	SolicitadaEn pgtype.Timestamptz `json:"solicitada_en"`
}

func (q *Queries) CreateRightsRequest(ctx context.Context, arg CreateRightsRequestParams) (CreateRightsRequestRow, error) {
	row := q.db.QueryRow(ctx, createRightsRequest,
		arg.ID,
		arg.AccountID,
		arg.Kind,
		arg.Channel,
	)
	var i CreateRightsRequestRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.SolicitadaEn,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO public.sesion (
    id, usuario_id, token_hash, creada_en, ultima_actividad_en,
    expira_en, revocada_en, cliente_resumen
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type CreateSessionParams struct {
	ID             string             `json:"id"`
	AccountID      string             `json:"account_id"`
	TokenHash      string             `json:"token_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	ClientSummary  *string            `json:"client_summary"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastActivityAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.ClientSummary,
	)
	return err
}

const createTenantRole = `-- name: CreateTenantRole :exec
INSERT INTO public.rol_usuario (usuario_id, rol)
VALUES ($1, 'arrendatario')
`

func (q *Queries) CreateTenantRole(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, createTenantRole, accountID)
	return err
}

const createTermsAcceptance = `-- name: CreateTermsAcceptance :exec
INSERT INTO public.aceptacion_terminos (
    id, usuario_id, version_id, aceptada_en, canal
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateTermsAcceptanceParams struct {
	ID         string             `json:"id"`
	AccountID  string             `json:"account_id"`
	VersionID  string             `json:"version_id"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	Channel    string             `json:"channel"`
}

func (q *Queries) CreateTermsAcceptance(ctx context.Context, arg CreateTermsAcceptanceParams) error {
	_, err := q.db.Exec(ctx, createTermsAcceptance,
		arg.ID,
		arg.AccountID,
		arg.VersionID,
		arg.AcceptedAt,
		arg.Channel,
	)
	return err
}

const deleteExpiredPasswordHistory = `-- name: DeleteExpiredPasswordHistory :exec
DELETE FROM public.historial_clave_local
WHERE usuario_id = $1 AND retirar_en <= $2
`

type DeleteExpiredPasswordHistoryParams struct {
	AccountID string             `json:"account_id"`
	At        pgtype.Timestamptz `json:"at"`
}

func (q *Queries) DeleteExpiredPasswordHistory(ctx context.Context, arg DeleteExpiredPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordHistory, arg.AccountID, arg.At)
	return err
}

const enqueueCredentialChanged = `-- name: EnqueueCredentialChanged :exec
INSERT INTO public.outbox_evento_local (
    id, agregado_tipo, agregado_id, tipo, clave_deduplicacion, version, creada_en, disponible_en
) VALUES (
    $1, 'usuario', $2, 'identidad.credencial_cambiada',
    $3, 1, $4, $4
)
`

type EnqueueCredentialChangedParams struct {
	ID        string             `json:"id"`
	AccountID string             `json:"account_id"`
	DedupeKey string             `json:"dedupe_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) EnqueueCredentialChanged(ctx context.Context, arg EnqueueCredentialChangedParams) error {
	_, err := q.db.Exec(ctx, enqueueCredentialChanged,
		arg.ID,
		arg.AccountID,
		arg.DedupeKey,
		arg.CreatedAt,
	)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT
    id::text AS id,
    correo_original AS email,
    correo_normalizado AS normalized_email,
    hash_clave AS password_hash,
    estado AS state,
    creado_en AS created_at,
    actualizado_en AS updated_at,
    intentos_fallidos_consecutivos AS failed_attempts,
    bloqueado_hasta AS blocked_until, preferencia_uso AS use_preference
FROM public.usuario
WHERE id = $1
LIMIT 1
`

type GetAccountByIDRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	NormalizedEmail string             `json:"normalized_email"`
	PasswordHash    string             `json:"password_hash"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FailedAttempts  int32              `json:"failed_attempts"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UsePreference   *string            `json:"use_preference"`
}

func (q *Queries) GetAccountByID(ctx context.Context, id string) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedAttempts,
		&i.BlockedUntil,
		&i.UsePreference,
	)
	return i, err
}

const getAccountByNormalizedEmail = `-- name: GetAccountByNormalizedEmail :one
SELECT
    id::text AS id,
    correo_original AS email,
    correo_normalizado AS normalized_email,
    hash_clave AS password_hash,
    estado AS state,
    creado_en AS created_at,
    actualizado_en AS updated_at,
    intentos_fallidos_consecutivos AS failed_attempts,
    bloqueado_hasta AS blocked_until, preferencia_uso AS use_preference
FROM public.usuario
WHERE correo_normalizado = $1
LIMIT 1
`

type GetAccountByNormalizedEmailRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	NormalizedEmail string             `json:"normalized_email"`
	PasswordHash    string             `json:"password_hash"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FailedAttempts  int32              `json:"failed_attempts"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UsePreference   *string            `json:"use_preference"`
}

func (q *Queries) GetAccountByNormalizedEmail(ctx context.Context, normalizedEmail string) (GetAccountByNormalizedEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByNormalizedEmail, normalizedEmail)
	var i GetAccountByNormalizedEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedAttempts,
		&i.BlockedUntil,
		&i.UsePreference,
	)
	return i, err
}

const getAccountRoles = `-- name: GetAccountRoles :many
SELECT rol FROM public.rol_usuario WHERE usuario_id = $1 ORDER BY rol
`

func (q *Queries) GetAccountRoles(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAccountRoles, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rol string
		if err := rows.Scan(&rol); err != nil {
			return nil, err
		}
		items = append(items, rol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActionTokenByHash = `-- name: GetActionTokenByHash :one
SELECT
    id::text AS id,
    usuario_id::text AS account_id,
    proposito AS purpose,
    token_hash,
    creado_en AS created_at,
    expira_en AS expires_at,
    consumido_en AS consumed_at,
    invalidado_en AS invalidated_at,
    intentos AS attempts
FROM public.token_accion
WHERE token_hash = $1
LIMIT 1
`

type GetActionTokenByHashRow struct {
	ID            string             `json:"id"`
	AccountID     string             `json:"account_id"`
	Purpose       string             `json:"purpose"`
	TokenHash     string             `json:"token_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	InvalidatedAt pgtype.Timestamptz `json:"invalidated_at"`
	Attempts      int32              `json:"attempts"`
}

func (q *Queries) GetActionTokenByHash(ctx context.Context, tokenHash string) (GetActionTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getActionTokenByHash, tokenHash)
	var i GetActionTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.InvalidatedAt,
		&i.Attempts,
	)
	return i, err
}

const getActionTokenByID = `-- name: GetActionTokenByID :one
SELECT id::text AS id, usuario_id::text AS account_id, proposito AS purpose,
    token_hash, creado_en AS created_at, expira_en AS expires_at,
    consumido_en AS consumed_at, invalidado_en AS invalidated_at, intentos AS attempts
FROM public.token_accion WHERE id = $1
`

type GetActionTokenByIDRow struct {
	ID            string             `json:"id"`
	AccountID     string             `json:"account_id"`
	Purpose       string             `json:"purpose"`
	TokenHash     string             `json:"token_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	InvalidatedAt pgtype.Timestamptz `json:"invalidated_at"`
	Attempts      int32              `json:"attempts"`
}

func (q *Queries) GetActionTokenByID(ctx context.Context, id string) (GetActionTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, getActionTokenByID, id)
	var i GetActionTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.InvalidatedAt,
		&i.Attempts,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT usuario_id::text AS account_id, nombre_visible, telefono_normalizado,
       actualizado_en
FROM public.perfil_usuario
WHERE usuario_id = $1
`

type GetProfileRow struct {
	AccountID           string             `json:"account_id"`
	NombreVisible       string             `json:"nombre_visible"`
	TelefonoNormalizado *string            `json:"telefono_normalizado"`
	ActualizadoEn       pgtype.Timestamptz `json:"actualizado_en"`
}

// M02 profile queries are always scoped to the authenticated account ID.
func (q *Queries) GetProfile(ctx context.Context, accountID string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, accountID)
	var i GetProfileRow
	err := row.Scan(
		&i.AccountID,
		&i.NombreVisible,
		&i.TelefonoNormalizado,
		&i.ActualizadoEn,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    id::text AS id,
    usuario_id::text AS account_id,
    token_hash,
    creada_en AS created_at,
    ultima_actividad_en AS last_activity_at,
    expira_en AS expires_at,
    revocada_en AS revoked_at,
    COALESCE(cliente_resumen, '') AS client_summary
FROM public.sesion
WHERE token_hash = $1
LIMIT 1
`

type GetSessionByTokenHashRow struct {
	ID             string             `json:"id"`
	AccountID      string             `json:"account_id"`
	TokenHash      string             `json:"token_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	ClientSummary  string             `json:"client_summary"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientSummary,
	)
	return i, err
}

const getTermsVersion = `-- name: GetTermsVersion :one
SELECT
    id::text AS id,
    codigo AS code,
    tipo AS type,
    hash_sha256 AS sha256,
    publicada_en AS published_at
FROM public.version_terminos
WHERE id = $1
LIMIT 1
`

type GetTermsVersionRow struct {
	ID          string             `json:"id"`
	Code        string             `json:"code"`
	Type        string             `json:"type"`
	Sha256      string             `json:"sha256"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetTermsVersion(ctx context.Context, id string) (GetTermsVersionRow, error) {
	row := q.db.QueryRow(ctx, getTermsVersion, id)
	var i GetTermsVersionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Sha256,
		&i.PublishedAt,
	)
	return i, err
}

const getVerificationTokenByID = `-- name: GetVerificationTokenByID :one
SELECT id::text AS id, usuario_id::text AS account_id, proposito AS purpose,
    token_hash, creado_en AS created_at, expira_en AS expires_at,
    consumido_en AS consumed_at, invalidado_en AS invalidated_at, intentos AS attempts
FROM public.token_accion WHERE id = $1 AND proposito = 'verificar_correo'
`

type GetVerificationTokenByIDRow struct {
	ID            string             `json:"id"`
	AccountID     string             `json:"account_id"`
	Purpose       string             `json:"purpose"`
	TokenHash     string             `json:"token_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	InvalidatedAt pgtype.Timestamptz `json:"invalidated_at"`
	Attempts      int32              `json:"attempts"`
}

func (q *Queries) GetVerificationTokenByID(ctx context.Context, id string) (GetVerificationTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, getVerificationTokenByID, id)
	var i GetVerificationTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.InvalidatedAt,
		&i.Attempts,
	)
	return i, err
}

const invalidateActiveActionTokens = `-- name: InvalidateActiveActionTokens :execrows
UPDATE public.token_accion
SET invalidado_en = $1
WHERE usuario_id = $2
  AND proposito = $3
  AND consumido_en IS NULL
  AND invalidado_en IS NULL
  AND expira_en > $1
  AND intentos < 5
`

type InvalidateActiveActionTokensParams struct {
	InvalidatedAt pgtype.Timestamptz `json:"invalidated_at"`
	AccountID     string             `json:"account_id"`
	Purpose       string             `json:"purpose"`
}

func (q *Queries) InvalidateActiveActionTokens(ctx context.Context, arg InvalidateActiveActionTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateActiveActionTokens, arg.InvalidatedAt, arg.AccountID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOwnRightsRequests = `-- name: ListOwnRightsRequests :many
SELECT id::text AS id, tipo AS kind, estado AS state, solicitada_en
FROM public.solicitud_titular
WHERE usuario_id = $1
ORDER BY solicitada_en DESC, id DESC
`

type ListOwnRightsRequestsRow struct {
	ID           string             `json:"id"`
	Kind         string             `json:"kind"`
	State        string             `json:"state"`
	SolicitadaEn pgtype.Timestamptz `json:"solicitada_en"`
}

func (q *Queries) ListOwnRightsRequests(ctx context.Context, accountID string) ([]ListOwnRightsRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOwnRightsRequests, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnRightsRequestsRow
	for rows.Next() {
		var i ListOwnRightsRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.State,
			&i.SolicitadaEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPasswordHistory = `-- name: ListPasswordHistory :many
SELECT hash_clave
FROM public.historial_clave_local
WHERE usuario_id = $1 AND retirar_en > $2
ORDER BY dejo_de_ser_vigente_en DESC, id
`

type ListPasswordHistoryParams struct {
	AccountID string             `json:"account_id"`
	At        pgtype.Timestamptz `json:"at"`
}

func (q *Queries) ListPasswordHistory(ctx context.Context, arg ListPasswordHistoryParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPasswordHistory, arg.AccountID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var hash_clave string
		if err := rows.Scan(&hash_clave); err != nil {
			return nil, err
		}
		items = append(items, hash_clave)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountByActionTokenID = `-- name: LockAccountByActionTokenID :one
SELECT u.id::text AS id, u.correo_original AS email, u.correo_normalizado AS normalized_email,
    u.hash_clave AS password_hash, u.estado AS state, u.creado_en AS created_at,
    u.actualizado_en AS updated_at, u.intentos_fallidos_consecutivos AS failed_attempts,
    u.bloqueado_hasta AS blocked_until, preferencia_uso AS use_preference
FROM public.usuario u JOIN public.token_accion t ON t.usuario_id = u.id
WHERE t.id = $1
FOR UPDATE OF u
`

type LockAccountByActionTokenIDRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	NormalizedEmail string             `json:"normalized_email"`
	PasswordHash    string             `json:"password_hash"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FailedAttempts  int32              `json:"failed_attempts"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UsePreference   *string            `json:"use_preference"`
}

func (q *Queries) LockAccountByActionTokenID(ctx context.Context, tokenID string) (LockAccountByActionTokenIDRow, error) {
	row := q.db.QueryRow(ctx, lockAccountByActionTokenID, tokenID)
	var i LockAccountByActionTokenIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedAttempts,
		&i.BlockedUntil,
		&i.UsePreference,
	)
	return i, err
}

const lockAccountByEmail = `-- name: LockAccountByEmail :one
SELECT id::text AS id, correo_original AS email, correo_normalizado AS normalized_email,
    hash_clave AS password_hash, estado AS state, creado_en AS created_at,
    actualizado_en AS updated_at, intentos_fallidos_consecutivos AS failed_attempts,
    bloqueado_hasta AS blocked_until, preferencia_uso AS use_preference
FROM public.usuario
WHERE correo_normalizado = $1
FOR UPDATE
`

type LockAccountByEmailRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	NormalizedEmail string             `json:"normalized_email"`
	PasswordHash    string             `json:"password_hash"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FailedAttempts  int32              `json:"failed_attempts"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UsePreference   *string            `json:"use_preference"`
}

func (q *Queries) LockAccountByEmail(ctx context.Context, normalizedEmail string) (LockAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, lockAccountByEmail, normalizedEmail)
	var i LockAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedAttempts,
		&i.BlockedUntil,
		&i.UsePreference,
	)
	return i, err
}

const lockAccountBySessionHash = `-- name: LockAccountBySessionHash :one
SELECT u.id::text AS id, u.correo_original AS email, u.correo_normalizado AS normalized_email,
    u.hash_clave AS password_hash, u.estado AS state, u.creado_en AS created_at,
    u.actualizado_en AS updated_at, u.intentos_fallidos_consecutivos AS failed_attempts,
    u.bloqueado_hasta AS blocked_until, preferencia_uso AS use_preference
FROM public.usuario u JOIN public.sesion s ON s.usuario_id = u.id
WHERE s.token_hash = $1
FOR UPDATE OF u
`

type LockAccountBySessionHashRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	NormalizedEmail string             `json:"normalized_email"`
	PasswordHash    string             `json:"password_hash"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FailedAttempts  int32              `json:"failed_attempts"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UsePreference   *string            `json:"use_preference"`
}

func (q *Queries) LockAccountBySessionHash(ctx context.Context, tokenHash string) (LockAccountBySessionHashRow, error) {
	row := q.db.QueryRow(ctx, lockAccountBySessionHash, tokenHash)
	var i LockAccountBySessionHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedAttempts,
		&i.BlockedUntil,
		&i.UsePreference,
	)
	return i, err
}

const lockAccountByVerificationID = `-- name: LockAccountByVerificationID :one
SELECT u.id::text AS id, u.correo_original AS email, u.correo_normalizado AS normalized_email,
    u.hash_clave AS password_hash, u.estado AS state, u.creado_en AS created_at,
    u.actualizado_en AS updated_at, u.intentos_fallidos_consecutivos AS failed_attempts,
    u.bloqueado_hasta AS blocked_until, preferencia_uso AS use_preference
FROM public.usuario u JOIN public.token_accion t ON t.usuario_id = u.id
WHERE t.id = $1 AND t.proposito = 'verificar_correo'
FOR UPDATE OF u
`

type LockAccountByVerificationIDRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	NormalizedEmail string             `json:"normalized_email"`
	PasswordHash    string             `json:"password_hash"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FailedAttempts  int32              `json:"failed_attempts"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UsePreference   *string            `json:"use_preference"`
}

func (q *Queries) LockAccountByVerificationID(ctx context.Context, tokenID string) (LockAccountByVerificationIDRow, error) {
	row := q.db.QueryRow(ctx, lockAccountByVerificationID, tokenID)
	var i LockAccountByVerificationIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedAttempts,
		&i.BlockedUntil,
		&i.UsePreference,
	)
	return i, err
}

const lockAccountForActionToken = `-- name: LockAccountForActionToken :one
SELECT id::text
FROM public.usuario
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockAccountForActionToken(ctx context.Context, accountID string) (string, error) {
	row := q.db.QueryRow(ctx, lockAccountForActionToken, accountID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const purgeExpiredPasswordHistory = `-- name: PurgeExpiredPasswordHistory :exec
DELETE FROM public.historial_clave_local WHERE retirar_en <= $1
`

func (q *Queries) PurgeExpiredPasswordHistory(ctx context.Context, at pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, purgeExpiredPasswordHistory, at)
	return err
}

const recordActionTokenFailure = `-- name: RecordActionTokenFailure :execrows
UPDATE public.token_accion
SET intentos = intentos + 1
WHERE token_hash = $1
  AND expira_en > $2
  AND intentos < 5
  AND consumido_en IS NULL
  AND invalidado_en IS NULL
`

type RecordActionTokenFailureParams struct {
	TokenHash   string             `json:"token_hash"`
	AttemptedAt pgtype.Timestamptz `json:"attempted_at"`
}

func (q *Queries) RecordActionTokenFailure(ctx context.Context, arg RecordActionTokenFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordActionTokenFailure, arg.TokenHash, arg.AttemptedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordCredentialChangeAudit = `-- name: RecordCredentialChangeAudit :exec
INSERT INTO public.evento_auditoria_local (
    id, actor_id, recurso_tipo, recurso_id, accion, resultado, motivo_codigo,
    correlacion_id, ocurrido_en, retirar_en
) VALUES (
    $1, $2, 'usuario', $3,
    'identidad.credencial_cambiar', 'exito', 'clave_actualizada',
    $4, $5, $6
)
`

type RecordCredentialChangeAuditParams struct {
	ID            string             `json:"id"`
	ActorID       string             `json:"actor_id"`
	ResourceID    string             `json:"resource_id"`
	CorrelationID string             `json:"correlation_id"`
	At            pgtype.Timestamptz `json:"at"`
	RemoveAt      pgtype.Timestamptz `json:"remove_at"`
}

func (q *Queries) RecordCredentialChangeAudit(ctx context.Context, arg RecordCredentialChangeAuditParams) error {
	_, err := q.db.Exec(ctx, recordCredentialChangeAudit,
		arg.ID,
		arg.ActorID,
		arg.ResourceID,
		arg.CorrelationID,
		arg.At,
		arg.RemoveAt,
	)
	return err
}

const retryCredentialChangedNotice = `-- name: RetryCredentialChangedNotice :execrows
UPDATE public.outbox_evento_local
SET disponible_en = $1, lease_hasta = NULL,
    ultimo_error = 'mailpit_delivery_failed'
WHERE id = $2 AND entregada_en IS NULL AND lease_hasta = $3
`

type RetryCredentialChangedNoticeParams struct {
	RetryAt    pgtype.Timestamptz `json:"retry_at"`
	ID         string             `json:"id"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) RetryCredentialChangedNotice(ctx context.Context, arg RetryCredentialChangedNoticeParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryCredentialChangedNotice, arg.RetryAt, arg.ID, arg.LeaseUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeActiveSessions = `-- name: RevokeActiveSessions :exec
UPDATE public.sesion SET revocada_en = $1
WHERE usuario_id = $2 AND revocada_en IS NULL
`

type RevokeActiveSessionsParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	AccountID string             `json:"account_id"`
}

func (q *Queries) RevokeActiveSessions(ctx context.Context, arg RevokeActiveSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeActiveSessions, arg.RevokedAt, arg.AccountID)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE public.sesion
SET revocada_en = $1
WHERE id = $2 AND revocada_en IS NULL
`

type RevokeSessionParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        string             `json:"id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storePreviousPasswordHash = `-- name: StorePreviousPasswordHash :exec
INSERT INTO public.historial_clave_local (
    id, usuario_id, hash_clave, dejo_de_ser_vigente_en, retirar_en, creado_en
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type StorePreviousPasswordHashParams struct {
	ID                string             `json:"id"`
	AccountID         string             `json:"account_id"`
	PasswordHash      string             `json:"password_hash"`
	NoLongerCurrentAt pgtype.Timestamptz `json:"no_longer_current_at"`
	RemoveAt          pgtype.Timestamptz `json:"remove_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) StorePreviousPasswordHash(ctx context.Context, arg StorePreviousPasswordHashParams) error {
	_, err := q.db.Exec(ctx, storePreviousPasswordHash,
		arg.ID,
		arg.AccountID,
		arg.PasswordHash,
		arg.NoLongerCurrentAt,
		arg.RemoveAt,
		arg.CreatedAt,
	)
	return err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE public.sesion
SET ultima_actividad_en = $1
WHERE id = $2
  AND revocada_en IS NULL
  AND ultima_actividad_en <= $1
  AND expira_en > $1
  AND ultima_actividad_en + interval '30 minutes' > $1
`

type TouchSessionParams struct {
	ActivityAt pgtype.Timestamptz `json:"activity_at"`
	ID         string             `json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.ActivityAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLoginState = `-- name: UpdateLoginState :execrows
UPDATE public.usuario
SET estado = $1,
    intentos_fallidos_consecutivos = $2,
    bloqueado_hasta = $3,
    actualizado_en = now()
WHERE id = $4
`

type UpdateLoginStateParams struct {
	State          string             `json:"state"`
	FailedAttempts int32              `json:"failed_attempts"`
	BlockedUntil   pgtype.Timestamptz `json:"blocked_until"`
	ID             string             `json:"id"`
}

func (q *Queries) UpdateLoginState(ctx context.Context, arg UpdateLoginStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLoginState,
		arg.State,
		arg.FailedAttempts,
		arg.BlockedUntil,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE public.usuario SET hash_clave = $1, actualizado_en = now()
WHERE id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	AccountID    string `json:"account_id"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.AccountID)
	return err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO public.perfil_usuario (usuario_id, nombre_visible, telefono_normalizado, actualizado_en)
VALUES ($1, $2, $3, now())
ON CONFLICT (usuario_id) DO UPDATE
SET nombre_visible = EXCLUDED.nombre_visible,
    telefono_normalizado = EXCLUDED.telefono_normalizado,
    actualizado_en = now()
RETURNING usuario_id::text AS account_id, nombre_visible, telefono_normalizado,
          actualizado_en
`

type UpsertProfileParams struct {
	AccountID   string  `json:"account_id"`
	DisplayName string  `json:"display_name"`
	Phone       *string `json:"phone"`
}

type UpsertProfileRow struct {
	AccountID           string             `json:"account_id"`
	NombreVisible       string             `json:"nombre_visible"`
	TelefonoNormalizado *string            `json:"telefono_normalizado"`
	ActualizadoEn       pgtype.Timestamptz `json:"actualizado_en"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProfile, arg.AccountID, arg.DisplayName, arg.Phone)
	var i UpsertProfileRow
	err := row.Scan(
		&i.AccountID,
		&i.NombreVisible,
		&i.TelefonoNormalizado,
		&i.ActualizadoEn,
	)
	return i, err
}
