// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AceptacionTermino struct {
	ID         string             `json:"id"`
	UsuarioID  string             `json:"usuario_id"`
	VersionID  string             `json:"version_id"`
	AceptadaEn pgtype.Timestamptz `json:"aceptada_en"`
	Canal      string             `json:"canal"`
}

type PerfilUsuario struct {
	UsuarioID           string             `json:"usuario_id"`
	NombreVisible       string             `json:"nombre_visible"`
	TelefonoNormalizado *string            `json:"telefono_normalizado"`
	ActualizadoEn       pgtype.Timestamptz `json:"actualizado_en"`
}

type RolUsuario struct {
	UsuarioID    string             `json:"usuario_id"`
	Rol          string             `json:"rol"`
	ConcedidoEn  pgtype.Timestamptz `json:"concedido_en"`
	ConcedidoPor pgtype.UUID        `json:"concedido_por"`
}

type Sesion struct {
	ID                string             `json:"id"`
	UsuarioID         string             `json:"usuario_id"`
	TokenHash         string             `json:"token_hash"`
	CreadaEn          pgtype.Timestamptz `json:"creada_en"`
	UltimaActividadEn pgtype.Timestamptz `json:"ultima_actividad_en"`
	ExpiraEn          pgtype.Timestamptz `json:"expira_en"`
	RevocadaEn        pgtype.Timestamptz `json:"revocada_en"`
	ClienteResumen    *string            `json:"cliente_resumen"`
}

type SolicitudTitular struct {
	ID           string             `json:"id"`
	UsuarioID    string             `json:"usuario_id"`
	Tipo         string             `json:"tipo"`
	Canal        string             `json:"canal"`
	Estado       string             `json:"estado"`
	SolicitadaEn pgtype.Timestamptz `json:"solicitada_en"`
}

type TokenAccion struct {
	ID           string             `json:"id"`
	UsuarioID    string             `json:"usuario_id"`
	Proposito    string             `json:"proposito"`
	TokenHash    string             `json:"token_hash"`
	CreadoEn     pgtype.Timestamptz `json:"creado_en"`
	ExpiraEn     pgtype.Timestamptz `json:"expira_en"`
	ConsumidoEn  pgtype.Timestamptz `json:"consumido_en"`
	InvalidadoEn pgtype.Timestamptz `json:"invalidado_en"`
	Intentos     int32              `json:"intentos"`
}

type Usuario struct {
	ID                           string             `json:"id"`
	CorreoOriginal               string             `json:"correo_original"`
	CorreoNormalizado            string             `json:"correo_normalizado"`
	HashClave                    string             `json:"hash_clave"`
	Estado                       string             `json:"estado"`
	CreadoEn                     pgtype.Timestamptz `json:"creado_en"`
	ActualizadoEn                pgtype.Timestamptz `json:"actualizado_en"`
	BajaSolicitadaEn             pgtype.Timestamptz `json:"baja_solicitada_en"`
	IntentosFallidosConsecutivos int32              `json:"intentos_fallidos_consecutivos"`
	BloqueadoHasta               pgtype.Timestamptz `json:"bloqueado_hasta"`
}

type VersionTermino struct {
	ID          string             `json:"id"`
	Codigo      string             `json:"codigo"`
	Tipo        string             `json:"tipo"`
	HashSha256  string             `json:"hash_sha256"`
	PublicadaEn pgtype.Timestamptz `json:"publicada_en"`
}
