// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActiveCredentialNoticeRecipientEmail(ctx context.Context, accountID string) (string, error)
	CancelInactiveCredentialNotice(ctx context.Context, arg CancelInactiveCredentialNoticeParams) (int64, error)
	CancelInactiveCredentialNotices(ctx context.Context, arg CancelInactiveCredentialNoticesParams) (int64, error)
	ClaimCredentialChangedNotice(ctx context.Context, arg ClaimCredentialChangedNoticeParams) (ClaimCredentialChangedNoticeRow, error)
	CompleteCredentialChangedNotice(ctx context.Context, arg CompleteCredentialChangedNoticeParams) (int64, error)
	ConsumeActionToken(ctx context.Context, arg ConsumeActionTokenParams) (int64, error)
	CountActionTokenEmissions(ctx context.Context, arg CountActionTokenEmissionsParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateActionToken(ctx context.Context, arg CreateActionTokenParams) error
	CreateCredentialNoticeRecoveryCycle(ctx context.Context, arg CreateCredentialNoticeRecoveryCycleParams) error
	CreateRightsRequest(ctx context.Context, arg CreateRightsRequestParams) (CreateRightsRequestRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTenantRole(ctx context.Context, accountID string) error
	CreateTermsAcceptance(ctx context.Context, arg CreateTermsAcceptanceParams) error
	DeleteExpiredPasswordHistory(ctx context.Context, arg DeleteExpiredPasswordHistoryParams) error
	EnqueueCredentialChanged(ctx context.Context, arg EnqueueCredentialChangedParams) error
	FindCredentialNoticeCycleByKey(ctx context.Context, arg FindCredentialNoticeCycleByKeyParams) (FindCredentialNoticeCycleByKeyRow, error)
	GetAccountByID(ctx context.Context, id string) (GetAccountByIDRow, error)
	GetAccountByNormalizedEmail(ctx context.Context, normalizedEmail string) (GetAccountByNormalizedEmailRow, error)
	GetAccountRoles(ctx context.Context, accountID string) ([]string, error)
	GetActionTokenByHash(ctx context.Context, tokenHash string) (GetActionTokenByHashRow, error)
	GetActionTokenByID(ctx context.Context, id string) (GetActionTokenByIDRow, error)
	// M02 profile queries are always scoped to the authenticated account ID.
	GetProfile(ctx context.Context, accountID string) (GetProfileRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetTermsVersion(ctx context.Context, id string) (GetTermsVersionRow, error)
	GetVerificationTokenByID(ctx context.Context, id string) (GetVerificationTokenByIDRow, error)
	InvalidateActiveActionTokens(ctx context.Context, arg InvalidateActiveActionTokensParams) (int64, error)
	ListOwnRightsRequests(ctx context.Context, accountID string) ([]ListOwnRightsRequestsRow, error)
	ListPasswordHistory(ctx context.Context, arg ListPasswordHistoryParams) ([]string, error)
	ListTerminalCredentialNotices(ctx context.Context) ([]ListTerminalCredentialNoticesRow, error)
	LockAccountByActionTokenID(ctx context.Context, tokenID string) (LockAccountByActionTokenIDRow, error)
	LockAccountByEmail(ctx context.Context, normalizedEmail string) (LockAccountByEmailRow, error)
	LockAccountBySessionHash(ctx context.Context, tokenHash string) (LockAccountBySessionHashRow, error)
	LockAccountByVerificationID(ctx context.Context, tokenID string) (LockAccountByVerificationIDRow, error)
	LockAccountForActionToken(ctx context.Context, accountID string) (string, error)
	LockCredentialNoticeForRecovery(ctx context.Context, id string) (LockCredentialNoticeForRecoveryRow, error)
	PurgeExpiredCredentialNotices(ctx context.Context, arg PurgeExpiredCredentialNoticesParams) (int64, error)
	PurgeExpiredPasswordHistory(ctx context.Context, at pgtype.Timestamptz) error
	RecordActionTokenFailure(ctx context.Context, arg RecordActionTokenFailureParams) (int64, error)
	RecordCredentialChangeAudit(ctx context.Context, arg RecordCredentialChangeAuditParams) error
	RecordCredentialNoticeRecoveryAudit(ctx context.Context, arg RecordCredentialNoticeRecoveryAuditParams) error
	ReopenCredentialNotice(ctx context.Context, arg ReopenCredentialNoticeParams) (int64, error)
	RetryCredentialChangedNotice(ctx context.Context, arg RetryCredentialChangedNoticeParams) (int64, error)
	RevokeActiveSessions(ctx context.Context, arg RevokeActiveSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	StartCredentialNoticeCycle(ctx context.Context, arg StartCredentialNoticeCycleParams) error
	StorePreviousPasswordHash(ctx context.Context, arg StorePreviousPasswordHashParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error)
	UpdateLoginState(ctx context.Context, arg UpdateLoginStateParams) (int64, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error)
}

var _ Querier = (*Queries)(nil)
