// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package verificationdb

import (
	"context"
)

type Querier interface {
	CreateVerification(ctx context.Context, arg CreateVerificationParams) (CreateVerificationRow, error)
	CreateVerificationRetry(ctx context.Context, arg CreateVerificationRetryParams) (CreateVerificationRetryRow, error)
	GetOwnVerification(ctx context.Context, arg GetOwnVerificationParams) (GetOwnVerificationRow, error)
	GetVerificationByIdempotency(ctx context.Context, arg GetVerificationByIdempotencyParams) (GetVerificationByIdempotencyRow, error)
	ListOwnVerifications(ctx context.Context, ownerID string) ([]ListOwnVerificationsRow, error)
	ListPendingVerifications(ctx context.Context) ([]ListPendingVerificationsRow, error)
	LockPriorVerificationForRetry(ctx context.Context, arg LockPriorVerificationForRetryParams) (LockPriorVerificationForRetryRow, error)
	ReviewVerification(ctx context.Context, arg ReviewVerificationParams) (ReviewVerificationRow, error)
}

var _ Querier = (*Queries)(nil)
