// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package verificationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :one
INSERT INTO public.verificacion (
    id, usuario_id, tipo, estado, proveedor_ref, referencia_evidencia,
    clave_idempotencia, creada_en
) VALUES (
    $1, $2, $3, 'en_revision',
    'local-fixture-v1', $4, $5, $6
)
ON CONFLICT (usuario_id, clave_idempotencia) DO NOTHING
RETURNING id::text AS id, usuario_id::text AS owner_id, tipo AS type,
    estado AS state, proveedor_ref AS provider, referencia_evidencia AS evidence_ref,
    COALESCE(reintento_de::text, ''::text) AS retry_of,
    COALESCE(motivo_codigo, '') AS reason_code,
    creada_en AS created_at, resuelta_en AS resolved_at,
    clave_idempotencia AS idempotency_key
`

type CreateVerificationParams struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	EvidenceRef    string             `json:"evidence_ref"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CreateVerificationRow struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	State          string             `json:"state"`
	Provider       string             `json:"provider"`
	EvidenceRef    string             `json:"evidence_ref"`
	RetryOf        interface{}        `json:"retry_of"`
	ReasonCode     string             `json:"reason_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IdempotencyKey string             `json:"idempotency_key"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (CreateVerificationRow, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.ID,
		arg.OwnerID,
		arg.Type,
		arg.EvidenceRef,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i CreateVerificationRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.State,
		&i.Provider,
		&i.EvidenceRef,
		&i.RetryOf,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createVerificationRetry = `-- name: CreateVerificationRetry :one
INSERT INTO public.verificacion (
    id, usuario_id, tipo, estado, proveedor_ref, referencia_evidencia,
    clave_idempotencia, reintento_de, creada_en
) VALUES (
    $1, $2, $3, 'en_revision',
    'local-fixture-v1', $4, $5,
    $6::text::uuid, $7
)
RETURNING id::text AS id, usuario_id::text AS owner_id, tipo AS type,
    estado AS state, proveedor_ref AS provider, referencia_evidencia AS evidence_ref,
    COALESCE(reintento_de::text, ''::text) AS retry_of,
    COALESCE(motivo_codigo, '') AS reason_code,
    creada_en AS created_at, resuelta_en AS resolved_at,
    clave_idempotencia AS idempotency_key
`

type CreateVerificationRetryParams struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	EvidenceRef    string             `json:"evidence_ref"`
	IdempotencyKey string             `json:"idempotency_key"`
	RetryOf        string             `json:"retry_of"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CreateVerificationRetryRow struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	State          string             `json:"state"`
	Provider       string             `json:"provider"`
	EvidenceRef    string             `json:"evidence_ref"`
	RetryOf        interface{}        `json:"retry_of"`
	ReasonCode     string             `json:"reason_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IdempotencyKey string             `json:"idempotency_key"`
}

func (q *Queries) CreateVerificationRetry(ctx context.Context, arg CreateVerificationRetryParams) (CreateVerificationRetryRow, error) {
	row := q.db.QueryRow(ctx, createVerificationRetry,
		arg.ID,
		arg.OwnerID,
		arg.Type,
		arg.EvidenceRef,
		arg.IdempotencyKey,
		arg.RetryOf,
		arg.CreatedAt,
	)
	var i CreateVerificationRetryRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.State,
		&i.Provider,
		&i.EvidenceRef,
		&i.RetryOf,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getOwnVerification = `-- name: GetOwnVerification :one
SELECT id::text AS id, usuario_id::text AS owner_id, tipo AS type,
    estado AS state, proveedor_ref AS provider, referencia_evidencia AS evidence_ref,
    COALESCE(reintento_de::text, ''::text) AS retry_of,
    COALESCE(motivo_codigo, '') AS reason_code,
    creada_en AS created_at, resuelta_en AS resolved_at,
    clave_idempotencia AS idempotency_key
FROM public.verificacion
WHERE usuario_id = $1 AND id = $2
LIMIT 1
`

type GetOwnVerificationParams struct {
	OwnerID string `json:"owner_id"`
	ID      string `json:"id"`
}

type GetOwnVerificationRow struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	State          string             `json:"state"`
	Provider       string             `json:"provider"`
	EvidenceRef    string             `json:"evidence_ref"`
	RetryOf        interface{}        `json:"retry_of"`
	ReasonCode     string             `json:"reason_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IdempotencyKey string             `json:"idempotency_key"`
}

func (q *Queries) GetOwnVerification(ctx context.Context, arg GetOwnVerificationParams) (GetOwnVerificationRow, error) {
	row := q.db.QueryRow(ctx, getOwnVerification, arg.OwnerID, arg.ID)
	var i GetOwnVerificationRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.State,
		&i.Provider,
		&i.EvidenceRef,
		&i.RetryOf,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getVerificationByIdempotency = `-- name: GetVerificationByIdempotency :one
SELECT id::text AS id, usuario_id::text AS owner_id, tipo AS type,
    estado AS state, proveedor_ref AS provider, referencia_evidencia AS evidence_ref,
    COALESCE(reintento_de::text, ''::text) AS retry_of,
    COALESCE(motivo_codigo, '') AS reason_code,
    creada_en AS created_at, resuelta_en AS resolved_at,
    clave_idempotencia AS idempotency_key
FROM public.verificacion
WHERE usuario_id = $1 AND clave_idempotencia = $2
LIMIT 1
`

type GetVerificationByIdempotencyParams struct {
	OwnerID        string `json:"owner_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetVerificationByIdempotencyRow struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	State          string             `json:"state"`
	Provider       string             `json:"provider"`
	EvidenceRef    string             `json:"evidence_ref"`
	RetryOf        interface{}        `json:"retry_of"`
	ReasonCode     string             `json:"reason_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IdempotencyKey string             `json:"idempotency_key"`
}

func (q *Queries) GetVerificationByIdempotency(ctx context.Context, arg GetVerificationByIdempotencyParams) (GetVerificationByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getVerificationByIdempotency, arg.OwnerID, arg.IdempotencyKey)
	var i GetVerificationByIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.State,
		&i.Provider,
		&i.EvidenceRef,
		&i.RetryOf,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const listOwnVerifications = `-- name: ListOwnVerifications :many
SELECT id::text AS id, usuario_id::text AS owner_id, tipo AS type,
    estado AS state, proveedor_ref AS provider, referencia_evidencia AS evidence_ref,
    COALESCE(reintento_de::text, ''::text) AS retry_of,
    COALESCE(motivo_codigo, '') AS reason_code,
    creada_en AS created_at, resuelta_en AS resolved_at,
    clave_idempotencia AS idempotency_key
FROM public.verificacion
WHERE usuario_id = $1
ORDER BY creada_en DESC
`

type ListOwnVerificationsRow struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	State          string             `json:"state"`
	Provider       string             `json:"provider"`
	EvidenceRef    string             `json:"evidence_ref"`
	RetryOf        interface{}        `json:"retry_of"`
	ReasonCode     string             `json:"reason_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IdempotencyKey string             `json:"idempotency_key"`
}

func (q *Queries) ListOwnVerifications(ctx context.Context, ownerID string) ([]ListOwnVerificationsRow, error) {
	rows, err := q.db.Query(ctx, listOwnVerifications, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnVerificationsRow
	for rows.Next() {
		var i ListOwnVerificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Type,
			&i.State,
			&i.Provider,
			&i.EvidenceRef,
			&i.RetryOf,
			&i.ReasonCode,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingVerifications = `-- name: ListPendingVerifications :many
SELECT id::text AS id, usuario_id::text AS owner_id, tipo AS type,
    estado AS state, proveedor_ref AS provider, referencia_evidencia AS evidence_ref,
    COALESCE(reintento_de::text, ''::text) AS retry_of,
    COALESCE(motivo_codigo, '') AS reason_code,
    creada_en AS created_at, resuelta_en AS resolved_at,
    clave_idempotencia AS idempotency_key
FROM public.verificacion
WHERE estado = 'en_revision'
ORDER BY creada_en
`

type ListPendingVerificationsRow struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	State          string             `json:"state"`
	Provider       string             `json:"provider"`
	EvidenceRef    string             `json:"evidence_ref"`
	RetryOf        interface{}        `json:"retry_of"`
	ReasonCode     string             `json:"reason_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IdempotencyKey string             `json:"idempotency_key"`
}

func (q *Queries) ListPendingVerifications(ctx context.Context) ([]ListPendingVerificationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingVerifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingVerificationsRow
	for rows.Next() {
		var i ListPendingVerificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Type,
			&i.State,
			&i.Provider,
			&i.EvidenceRef,
			&i.RetryOf,
			&i.ReasonCode,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPriorVerificationForRetry = `-- name: LockPriorVerificationForRetry :one
SELECT tipo AS type, estado AS state
FROM public.verificacion
WHERE id = $1 AND usuario_id = $2
FOR UPDATE
`

type LockPriorVerificationForRetryParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

type LockPriorVerificationForRetryRow struct {
	Type  string `json:"type"`
	State string `json:"state"`
}

func (q *Queries) LockPriorVerificationForRetry(ctx context.Context, arg LockPriorVerificationForRetryParams) (LockPriorVerificationForRetryRow, error) {
	row := q.db.QueryRow(ctx, lockPriorVerificationForRetry, arg.ID, arg.OwnerID)
	var i LockPriorVerificationForRetryRow
	err := row.Scan(&i.Type, &i.State)
	return i, err
}

const reviewVerification = `-- name: ReviewVerification :one
UPDATE public.verificacion
SET estado = $1, revisor_id = $2::text::uuid,
    motivo_codigo = NULLIF($3::text, ''), resuelta_en = now()
WHERE id = $4 AND estado = 'en_revision'
RETURNING id::text AS id, usuario_id::text AS owner_id, tipo AS type,
    estado AS state, proveedor_ref AS provider, referencia_evidencia AS evidence_ref,
    COALESCE(reintento_de::text, ''::text) AS retry_of,
    COALESCE(motivo_codigo, '') AS reason_code,
    creada_en AS created_at, resuelta_en AS resolved_at,
    clave_idempotencia AS idempotency_key
`

type ReviewVerificationParams struct {
	State      string `json:"state"`
	ReviewerID string `json:"reviewer_id"`
	ReasonCode string `json:"reason_code"`
	ID         string `json:"id"`
}

type ReviewVerificationRow struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	Type           string             `json:"type"`
	State          string             `json:"state"`
	Provider       string             `json:"provider"`
	EvidenceRef    string             `json:"evidence_ref"`
	RetryOf        interface{}        `json:"retry_of"`
	ReasonCode     string             `json:"reason_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IdempotencyKey string             `json:"idempotency_key"`
}

func (q *Queries) ReviewVerification(ctx context.Context, arg ReviewVerificationParams) (ReviewVerificationRow, error) {
	row := q.db.QueryRow(ctx, reviewVerification,
		arg.State,
		arg.ReviewerID,
		arg.ReasonCode,
		arg.ID,
	)
	var i ReviewVerificationRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.State,
		&i.Provider,
		&i.EvidenceRef,
		&i.RetryOf,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.IdempotencyKey,
	)
	return i, err
}
